# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: Apache-2.0

min_version = "2026.7.5"

[settings]
experimental = true

[tools]
pipx = "1.16.7"
ruff = "0.16.3"

[bootstrap.packages]
# APT
"apt:apt-utils" = "latest"
"apt:createrepo-c" = "latest"
"apt:debsigs" = "latest"
"apt:gnupg" = "latest"
"apt:openssl" = "latest"
"apt:rpm" = "latest"

# DNF
"dnf:createrepo_c" = "latest"
"dnf:gnupg2" = "latest"
"dnf:openssl" = "latest"
"dnf:rpm" = "latest"

[task_config]
dir = "{{cwd}}"
includes = ["tasks"]
