# SPDX-FileCopyrightText: 2026 Nikolay Govorov
# SPDX-License-Identifier: 0BSD

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  release-tasks:
    name: Package and publish tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          version: 2026.7.5
          experimental: true
          install: false

      - name: Install dependencies
        run: mise bootstrap --locked --yes --update

      - name: Check Python
        run: |
          ruff check tasks tests
          ruff format --check tasks tests

      - name: Tests
        run: |
          tests/oci-tasks.py

          tests/package.py
          tests/package-integration.py

          tests/publish-integration.py
